// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZlXN9dPnilc_D-NHiEXIJcg5abRlpKT4',
    appId: '1:345407280554:web:3da0a146a3d9074d53c7d3',
    messagingSenderId: '345407280554',
    projectId: 'coursefireflutter',
    authDomain: 'coursefireflutter.firebaseapp.com',
    storageBucket: 'coursefireflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcmesbZIKwgaX1J5UnHlob78-qIUd8mBU',
    appId: '1:345407280554:android:87e02e60f1ef873353c7d3',
    messagingSenderId: '345407280554',
    projectId: 'coursefireflutter',
    storageBucket: 'coursefireflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMC_nWz1skF4QfrZLcp9SUz_gdQmt37lQ',
    appId: '1:345407280554:ios:a9556845b563a01a53c7d3',
    messagingSenderId: '345407280554',
    projectId: 'coursefireflutter',
    storageBucket: 'coursefireflutter.appspot.com',
    iosClientId: '345407280554-99m6s2bog0kvnn2ol0v59nln5lr6o93q.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMC_nWz1skF4QfrZLcp9SUz_gdQmt37lQ',
    appId: '1:345407280554:ios:a9556845b563a01a53c7d3',
    messagingSenderId: '345407280554',
    projectId: 'coursefireflutter',
    storageBucket: 'coursefireflutter.appspot.com',
    iosClientId: '345407280554-99m6s2bog0kvnn2ol0v59nln5lr6o93q.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteapp',
  );
}
